version: '3'

services:
  myapp:
    build: .
    image: mdyagual/books-api:latest
    ports:
      - 8080:8080
    environment:
      MONGODB_URI: "mongodb+srv://mdyagual:mdyagual@clustersofkau.hcyyx.mongodb.net/books-sofka-api?retryWrites=true&w=majority"
    deploy:
      replicas: 1