version: '3'

services:
  example-clean-architecture:
    build:
      context: .
      dockerfile: Dockerfile
    image: mdyagual/reactive-music:latest
    ports:
      - 8000:8000
    environment:
      MONGODB_URI: "mongodb+srv://mdyagual:mdyagual@clustersofkau.hcyyx.mongodb.net/books-sofka-api?retryWrites=true&w=majority"
    deploy:
      replicas: 1